name: case_study
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - pandas
  - scipy
  - yaml
  - wget
  - pip:
    - numpy==1.18.5
    - matplotlib
    - scikit-learn==0.20.3
    - tensorflow
